language: node_js
node_js:
  - "8.9.4"

script:
  - npm run build
  - npm test

deploy:
  edge:
    branch: v1.8.47 # See https://github.com/travis-ci/travis-ci/issues/9312
  provider: pages
  skip_cleanup: true
  local_dir: app
  github_token: $GITHUB_API_KEY
  target-branch: gh-pages
  on:
    branch: master
