language: node_js
node_js:
  - "8.9.4"

script:
  - npm run lint:sol
  - npm run build
  - npm run build-app
  - npm test

deploy:
  provider: pages
  local-dir: app/build
  skip-cleanup: true
  github-token: $GITHUB_API_KEY
  keep-history: true
  on:
    branch: master
