language: node_js
node_js:
  - "8.9.4"

script:
  - npm test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: app
  github_token: $GITHUB_API_KEY
  target-branch: gh-pages
  on:
    branch: master
